#!/bin/sh

unset GIT_DIR

echo "Moving to output directory"
cd `git config --get core.worktree` || exit

echo "Checking out the repo"
git checkout -f

echo "Calling the update script"
LANG="en_US.UTF-8" ROOT=`pwd` ./scripts/update
