#!/bin/bash

# This script is called after the website is updated

# Restart the webserver
sudo /etc/init.d/nginx restart

ROOT=/srv/http/cmetcalfe.ca

# Clone all the git submodules
cd $ROOT

git config -f .gitmodules --get-regexp '^submodule\..*\.path$' |
while read path_key path; do
    url_key=$(echo $path_key | sed 's/\.path/.url/')
    url=$(git config -f .gitmodules --get "$url_key")
    if [[ ! -d $path ]]; then
        # Module doesn't exist, clone it
        git clone $url $path
    else
        # Module exists, update it
        cd $path
        git checkout -- .
        git pull
        cd ..
    fi
done

# Restart Mag2tor
cd $ROOT
cd mag2tor
if [[ ! -d venv ]]; then
    # Mag2tor not configured, configure it
    virtualenv venv
    source venv/bin/activate
    pip install bottle
    pip install gunicorn
else
    source venv/bin/activate
fi
gunicorn app:app -b unix:///tmp/mag2tor.socket -w 1 -D
deactivate

cd $ROOT
