#!/bin/bash

# Requests/renews the Let's Encrypt certificate

source "$ROOT/scripts/constants"

# First run setup
cd "$HTTPS_CONFIG"
mkdir -p ".wellknown"
if [[ ! -f "dhparam.pem" ]]; then
    echo "No dhparam.pem found, generating one"
    openssl dhparam -out dhparam.pem 2048
fi

function restart_nginx {
    # Restart nginc and return the status
    sudo /etc/init.d/nginx restart
    sudo /etc/init.d/nginx status >/dev/null
    return $?
}

# Enable https, try running nginx, fall back to http
cd "$NGINX_CONFIG"
ln -sfn "https" "include"
if ! restart_nginx; then
    echo "Failed to run in HTTPS mode, falling back to HTTP..."
    ln -sfn "http" "include"
    if ! restart_nginx; then
        echo "Something is wrong with the nginx config - fix it and run again"
        exit 1
    fi
fi

# Call Let's Encrypt to make/renew HTTPS
"$ROOT/dehydrated/dehydrated" --cron --config "$HTTPS_CONFIG/config"
if [ $? -ne 0 ]; then
    echo "WARNING: Unable to renew certs, falling back to HTTP"
    ln -sfn "http" "include"
else
    echo "Cert renewal complete, enabling HTTPS"
    ln -sfn "https" "include"
fi

# Restart nginx
if ! restart_nginx; then
    echo "Failed to restart nginx, check the error log"
    exit 1
fi
