#!/bin/bash

# This script is called after the website is updated

source "$ROOT/scripts/constants"

setup_venv(){

    # Set up the virtualenv for the python app
    echo "Checking virtualenv for '$1'"

    if [[ ! -d "$1" ]]; then
        echo "No folder to setup virtualenv in found"
        return 1
    fi
    cd "$1"

    if [[ ! -d venv ]]; then
        echo "Virtualenv not found, setting one up"

        if ! virtualenv venv -p "$2"; then
            echo "Setting up virtualenv failed"
            return 1
        fi
    else
        echo "Found virtualenv, activating it"
    fi

    source venv/bin/activate
    if [[ -f requirements.txt ]]; then
        # Get the newest versions allowed by the requirements file
        pip install --upgrade -r requirements.txt
    fi

    return 0
}

run_gunicorn(){

    # Choose python version (default to system default)
    if [ "$#" -gt 1 ]; then
        pyversion="$2"
    else
        pyversion=python
    fi

    setup_venv "$1" "$pyversion"
    status=$?

    if [[ $status -ne 0 ]]; then
        # Failed to create the virtualenv, can't continue
        echo "Couldn't find or create the virtualenv, not starting the application"
        return
    fi

    # Always update to the latest version
    pip install --upgrade gunicorn

    # (Re)start gunicorn
    if [[ -f gunicorn.pid ]] && kill -HUP "`cat gunicorn.pid`"; then
        echo "Restarted gunicorn"
    else
        echo "Starting gunicorn"
        gunicorn app:app -b "unix:///tmp/"`basename "$1"`".socket" -w 1 -D -p gunicorn.pid
    fi

    deactivate
}

generate_site(){

    # Generate the config files
    generate_configs

    setup_venv "$ROOT/pelican" python2

    echo "Generating the site"
    pelican -s publishconf.py -o $OUTPUT/www content

    deactivate

    # Call the certificate renewal script
    "$ROOT/scripts/renew"
}

generate_configs(){
    # Copy configs into expected locations while replacing paths in them
    # Replace {{root}}, {{output}}, and {{https}} in config files as they're copied
    cd "$CONFIG_INPUT"
    for f in `find * -mindepth 1 -type f`; do
        mkdir -p "$CONFIG/"`dirname "$f"`
        sed -e "s|{{root}}|$ROOT|g" \
            -e "s|{{output}}|$OUTPUT|g" \
            -e "s|{{https}}|$HTTPS_CONFIG|g" \
            "$f" > "$CONFIG/$f"

    done
}

echo "Running update script"

echo "Checking dependencies"
dependencies=( "python2" "python3" "virtualenv" )
for command in ${dependencies[@]}; do
    if ! command -v $command &>/dev/null; then
        echo "Missing dependency '$command', exiting"
        exit 1
    fi
done

# Update the submodules
echo "Updating submodules"
git submodule update --init --recursive --force

# Run/restart webapps
run_gunicorn $OUTPUT/mag2tor python3
run_gunicorn $OUTPUT/gh-i2p python2

# Generate the site
generate_site
